export const UPDATE_HOTEL_START = 'UPDATE_HOTEL_START';
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS';
export const UPDATE_HOTEL_FAIL = 'UPDATE_HOTEL_FAIL';

export const FETCH_HOTELS_START = 'FETCH_HOTELS_START';
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const FETCH_HOTELS_FAIL = 'FETCH_HOTELS_FAIL';

export const CREATE_HOTEL_START = 'CREATE_HOTEL_START';
export const CREATE_HOTEL_SUCCESS = 'CREATE_HOTEL_SUCCESS';
export const CREATE_HOTEL_FAIL = 'CREATE_HOTEL_FAIL';

export const FETCH_HOTEL_BYID_START = 'FETCH_HOTEL_BYID_START';
export const FETCH_HOTEL_BYID_SUCCESS = 'FETCH_HOTEL_BYID_SUCCESS';
export const FETCH_HOTEL_BYID_FAIL = 'FETCH_HOTEL_BYID_FAIL';