export const REQUEST_HOTEL_START = 'REQUEST_HOTEL_START';
export const REQUEST_HOTEL_FAIL = 'REQUEST_HOTEL_FAIL';

export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS';
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const CREATE_HOTEL_SUCCESS = 'CREATE_HOTEL_SUCCESS';
export const FETCH_HOTEL_BYID_SUCCESS = 'FETCH_HOTEL_BYID_SUCCESS';
export const STORE_HOTEL_ID = 'STORE_HOTEL_ID';
