export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_EXPIRED_TOKEN = 'USER_EXPIRED_TOKEN';